### ISSUE TITLE
Onion address support

### ISSUE THREAD

**Issue by jochemin** [LN-Zap/lndconnect#13]
When I create the QR the public IP is added to qr code. It's possible to add the onion address? It is in the uri.

**Comment by ottosuess** [comment]
you can use the `--host=` argument to set a custom host.

you'll need to scan the qr code with a client that supports tor though. don't know if there is one right now.

**Comment by jochemin** [comment]
Ok, just making some tests. Thank you

**Comment by JimmyMow** [comment]
@jochemin does `--host` resolve your issue? if so, i'm going to close this
