### ISSUE TITLE
[Feature Request] lnd-connect should not require certificate

### ISSUE THREAD

**Issue by NicolasDorier** [LN-Zap/lndconnect#6]
[LND Connect](https://github.com/LN-Zap/zap-iOS/blob/master/docs/lnd_connect_uri.md) mentions that the certificate must be provided.

In BTCPay, I don't provide the certificate to the users because the certificate get renewed every 3 months automatically, and are trusted by the root store of the machine of the user.

As is, if BTCPay support lnd connect, the user will need 
1. Repair every 3 months
2. Use complicated process to download the certificate through their browser and convert it in the right cer format for Zap consumption

**Comment by andrerfneves** [comment]
<img width="764" alt="screen shot 2019-02-13 at 2 58 49 pm" src="https://user-images.githubusercontent.com/2574011/52739908-e3394e80-2f9f-11e9-8f6e-c6ccadfd4600.png">

Facing this issue right now. Unable to get my TLS.cert from BTCPay. @NicolasDorier is there a way to do that by SSH'ing into the server? Where would the TLS cert be located? Wouldn't I need to re-download it every 3 mos then?

**Comment by NicolasDorier** [comment]
@andrerfneves:

1. The certificate is public, no need of SSHing, you can just make a TLS connection and retrieve it.
2. No need to redownload, because every OS have their own trust store and are able to validate the certificate on the behalf of the app.

If you use grpc directly or ln-service API, check https://github.com/alexbosworth/ln-service/pull/71

**Comment by andrerfneves** [comment]
@NicolasDorier thanks for the information. I think I'm almost there but continue to get an error on LNDConnect. I believe I'm not getting my certificate correctly?

`openssl s_client -connect btcpay.MYURL:443 -prexit`

Output includes
```
-----BEGIN CERTIFICATE-----
.............
-----END CERTIFICATE-----
```

I take that and turn it into a `tls.cert` file, then along with my admin macaroon copied from the Services > LND GRPC information (admin.macaroon line), I run `lndconnect --adminmacaroonpath=admin.macaroon --tlscertpath=tls.cert`.

The QRCode isn't a square, it's more of a long rectangle and it took a little second to render which makes me think this is not the correct way to fetch my certificate. I also tried it with the `-j` flag which outputs the code that I can paste to the iOS app. I tried that as well but it says `Could not connect to server` even though the IP/Port are correct --> which means it must be the macaroon or the certificate.

Would you be able to shed some light on this for me?
Really appreciate the help.

**Comment by ottosuess** [comment]
On BTCPay Server there should be QR Code somewhere that you can just scan to connect the Zap iOS app. Isn't that working for you?

**Comment by andrerfneves** [comment]
> On BTCPay Server there should be QR Code somewhere that you can just scan to connect the Zap iOS app. Isn't that working for you?

I assumed that'd work too, but the QRCode reader just hangs there. I've made sure the image ism sharp and centered and all that. 

> It takes a few seconds to render the QR Code because lndconnect is loading your public ip from an external service. And the QRCode isn't a perfect square because of the font in your terminal. That's all normal.

That makes sense, but I'm on font-size 2px and I can't even see the whole QRCode since it's that long (which is why I think it's not correct). The camera/QRCode reader also doesn't seem to be able to read it (but probably because it can't see it all). 

I tried the `-j` option and pasted into Zap iOS. The URL/Port are correct but  get the `could not connect` issue.

Really puzzled by this as I think I'm doing all of the correct things. Maybe I can redownload the iOS app? Not sure at this point.

Thanks for helping @ottosuess

**Comment by JimmyMow** [comment]
That's strange, I just tested scanning the BTCPay Server QR code from my Zap iOS app and it worked as expected. What QR code are you scanning @andrerfneves? Could be the wrong one potentially?

The one I use is in `Server Settings` -> `Services` -> `BTC LND gRPC` -> `QR Code connection`

**Comment by andrerfneves** [comment]
@JimmyMow Yeah that's exactly the one. I would put a screenshot of the QRCode but that'd give folks access to my node.

<img width="1680" alt="screen shot 2019-02-14 at 11 21 50 am" src="https://user-images.githubusercontent.com/2574011/52800920-cc036b00-304a-11e9-9dc8-68df8484910e.png">

I click `Show QR Code` and then try scanning that code. Could it be my camera? I doubt that. Also just tried reinstalling the app but same results.

**Comment by ottosuess** [comment]
@andrerfneves if it isn't working you can send me a screenshot of the QR code so i can debug this issue. (i'm on lnd and zap slacks)

**Comment by andrerfneves** [comment]
For future reference, I was using a dark background theme for BTCPayServer and therefore my camera could not read the QRCode. If you're facing the same/similar issue, download another QR Code reader application and see if that's able to read your QRCode. If it can't, chances are the background color of your theme is affecting things.

It works well when you scan the QR Code inside Zap app and your background is white.

Thanks @JimmyMow @ottosuess @NicolasDorier for the help.

@NicolasDorier, even though this is not part of core BTCPayServer because I was using a custom theme, should I raise an issue to create a border around the QRCode so that it can work with dark background themes? Or do you think that's outside of core BTCPayServer? Any thoughts?

**Comment by NicolasDorier** [comment]
> @NicolasDorier thanks for the information. I think I'm almost there but continue to get an error on LNDConnect. I believe I'm not getting my certificate correctly?
> 
> `openssl s_client -connect btcpay.MYURL:443 -prexit`
> 
> Output includes
> 
> ```
> -----BEGIN CERTIFICATE-----
> .............
> -----END CERTIFICATE-----
> ```
> I take that and turn it into a `tls.cert` file, then along with my admin macaroon copied from the Services > LND GRPC information (admin.macaroon line), I run `lndconnect --adminmacaroonpath=admin.macaroon --tlscertpath=tls.cert`.
> 
> The QRCode isn't a square, it's more of a long rectangle and it took a little second to render which makes me think this is not the correct way to fetch my certificate. I also tried it with the `-j` flag which outputs the code that I can paste to the iOS app. I tried that as well but it says `Could not connect to server` even though the IP/Port are correct --> which means it must be the macaroon or the certificate.
> 
> Would you be able to shed some light on this for me?
> Really appreciate the help.

@andrerfneves the cert you retrieve might not be the same as the one really used. I think NGINX is using SNI, which mean that openssl need to do add some hint something more to fetch the certificate. (this is done so a network scanner can't automatically search for btcpay server by pinging random IPs without knowing the domain name)

`openssl s_client -connect mainnet.demo.btcpayserver.org:443 -prexit` will not give you the same cert as delivered by https://mainnet.demo.btcpayserver.org/

**Comment by NicolasDorier** [comment]
This works `openssl s_client -connect mainnet.demo.btcpayserver.org:443 -servername mainnet.demo.btcpayserver.org -prexit` 

though you should not use it, instead just rely on the OS to validate the cert.

**Comment by andrerfneves** [comment]
Thanks @NicolasDorier

**Comment by mrfelton** [comment]
Probably we should update `lndconnect` to not require a certificate since it may not be needed if the node is already using a widely trusted certificate.

**Comment by ottosuess** [comment]
@mrfelton there is already a pr that needs your review: https://github.com/LN-Zap/lndconnect/pull/11 🔥
