### ISSUE TITLE
Incorrect cert encoding?

### ISSUE THREAD

**Issue by mandelmonkey** [LN-Zap/lndconnect#9]
I previously used zapconnect -j command and the "c" value ended with an "=" 
i.e.
```
ZTikgoU=","m":"AgE
```

However with lnd connect it is missing and my connection fails
i.e.
```
ZTikgoU","m":"AgE
```

I guess this is either a bug or because parsing the url wouldnt work if theres a ```=``` character? is any wallet implementing lndconnect expected to add the "="?

**Comment by ottosuess** [comment]
thats because its not base64 but base64url.

**Comment by mandelmonkey** [comment]
ah ok yeah noticed ```_``` changed to ```//```
ok will handle in the wallet
